project:
  type: website
  render:
    - "**/*.qmd"
  resources:
    - templates/

pagetitle: "{{< meta title >}} | Srikrishnan Group"
author-meta: "Vivek Srikrishnan"

website:
  title: "Lab Manual | Srikrishnan Group"
  description: "The lab manual for the Srikrishnan Research Group at Cornell University."
  site-url: "https://viveks.bee.cornell.edu/lab-manual"
  repo-url: "https://github.com/srikrishnan-lab/lab-manual"
  favicon: assets/logos/favicon.png
  twitter-card: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F7F7F7"
    left: |
      <span class="faux-block">© {{< var years >}} Vivek Srikrishnan</span>
      <span class="faux-block">All content licensed under<br>[Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: Made with
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)<br>
      See the [About Page](/about.qmd) for credit information.
    right:
      - icon: github
        href: https://github.com/srikrishnan-lab/lab-manual

  navbar:
    pinned: true
    search: true
    left:
      - text: "Contributing"
        href: contributing/index.qmd
      - text: "Expectations and Conduct"
        href: expectations/index.qmd
      - text: "Guides"
        href: guides/index.qmd
      - text: "Knowledge Base"
        href: kb/index.qmd
      - text: "Procedures"
        href: procedures/index.qmd
      - text: "Lab Manual"
        href: index.qmd

  sidebar:
    - title: "Expectations and Conduct"
      style: "floating"
      contents:
        - expectations/index.qmd
        - expectations/availability.qmd
        - expectations/harassment.qmd
        - expectations/health.qmd
        - expectations/open.qmd
        - expectations/roles.qmd
        - expectations/timeoff.qmd
    - title: "Guides"
      style: "floating"
      contents:
        - guides/index.qmd
        - guides/ai-tools.qmd
        - guides/authorship.qmd
        - guides/best-practices.qmd
        - guides/data-management.qmd
        - guides/figure-library.qmd
        - guides/figures.qmd
        - guides/github-zenodo.qmd
        - guides/group-workflow.qmd
        - guides/hopper.qmd
        - guides/hopper-access.qmd
        - guides/licenses.qmd
        - guides/meetings.qmd
        - guides/paper-checklist.qmd
        - guides/papers.qmd
        - guides/readinglist.qmd
        - guides/recommendations.qmd
    - title: "Knowledge Base"
      style: "floating"
      contents:
        - kb/index.qmd
        - kb/glossary.qmd
        - section: "Programming"
          contents:
            - kb/programming/conda.qmd
            - kb/programming/git.qmd
            - kb/programming/julia.qmd
            - kb/programming/latex.qmd
            - kb/programming/markdown.qmd
            - kb/programming/python.qmd
            - kb/programming/R.qmd
            - kb/programming/shell.qmd
        - section: "Program Requirements"
          contents:
            - kb/requirements/index.qmd
            - kb/requirements/minors.qmd
            - kb/requirements/ms.qmd
            - kb/requirements/phd.qmd
    - title: "Procedures"
      style: "floating"
      contents:
        - procedures/index.qmd
        - procedures/checklist.qmd
        - procedures/graduate.qmd
        - procedures/postdoc.qmd
        - procedures/undergrad.qmd
        - procedures/offboarding.qmd

format:
  html:
    theme: [spacelab, styles/custom.scss]
    toc: true
    code-link: true
    code-tools: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: a11y-light
    mainfont: Inter
    smooth-scroll: true
    link-external-newwindow: true
    date-format: YYYY