---
title: "Srikrishnan Group Lab Manual"
---

## Overview

Welcome to the lab guide for the [Srikrishnan Research Group](https://viveks.bee.cornell.edu) in the [Department of Biological & Environmental Engineering](https://bee.cals.cornell.edu) at [Cornell University](https://cornell.edu). The PI for the group is [Vivek Srikrishnan](https://viveks.me).

This manual details lab procedures, policies, and expectations for new and existing research group members. It is divided into the following main sections:

1. **Expectations and Conduct** outlines the expectations we have for each other and ourselves to ensure a functional, healthy, and productive lab group;
2. **Guides** provides guides for common lab tasks and materials;
3. **Knowledge Base** contains a rudimentary knowledge base with some basic resources and how-tos. This will probably get shifted to a different  format whenever I find the right one.
4. **Procedures** guides prospective and interested lab members through the process of joining the lab;

::: {.callout-note}
## Contributing

Detailed instructions for commenting and proposing changes are provided on the [Contributing](contributing/index.qmd) page.
:::

## Credit

See the [About page](about.qmd) for credit information.
