---
title: New Member Checklist
---

Go through this document and complete or initiate the appropriate steps. Contact Vivek if you have any questions.

- [ ] Create accounts:
    * [ ] Some type of calendar (Google calendar or Outlook)
    * [ ] [Github](http://github.com)
    * [ ] [Slack](https://slack.com)
    * [ ] [Trello](https://trello.com)
    * [ ] Some type of reference manager. Common choices are [Zotero](http://zotero.org) and [Paperpile](http://paperpile.com). Vivek uses Paperpile and can share papers within the group, but any reference manager will be fine. Zotero is free, but the lab can pay for a Paperpile account if preferred.
- [ ] Get added to group-wide resources by contacting Vivek once you've established accounts:
    * [ ] Github organization ([srikrishnan-lab](http://github.com/srikrishnan-lab))
    * [ ] Slack workspace
    * [ ] Hopper Cluster
    * [ ] Trello
- [ ] Add your information to the group website using a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests):
    * [ ] Photo (upload to /assets/img/members)
    * [ ] Website entry (in _data/people.yml):
        * Bio/Research interests
        * Contact and social media info
- [ ] Start reading the [onboarding papers](../guides/readinglist.qmd#general).
- [ ] Meet with Vivek and get access to Riley-Robb and the lab's space.
